export const LIST_PRODUCTS_REQUEST = 'LIST_PRODUCTS_REQUEST'
export const LIST_PRODUCTS_SUCCESS = 'LIST_PRODUCTS_SUCCESS'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAILURE = 'PRODUCT_DETAILS_FAILURE'